// <auto-generated />
namespace Assignment2.Migrations.ENET
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Comment_Intervention : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Comment_Intervention));
        
        string IMigrationMetadata.Id
        {
            get { return "201706070159016_Comment_Intervention"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
